

services:
    db:
      image: mysql:8
      restart: always
      volumes:
        - ./database/lib:/var/lib/mysql
      env_file:
        - ./.env
      container_name: mysql_db_tucita
      ports:
        - 3306:3306
      command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--log-error-verbosity=1']
  
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - 8000:8000
      volumes:
        - ./backend:/app
      env_file:
        - .env
      command: >
        sh -c "while ! nc -z db 3306; do sleep 1; done &&
              python manage.py migrate &&
              gunicorn --bind 0.0.0.0:8000 --limit-request-line 8190 app.wsgi"
      environment:
        - DJANGO_SETTINGS_MODULE=app.settings
        - DEBUG=0
      container_name: djapi_tucita_backend
      depends_on: 
        - db
      restart: always


    frontend:
      container_name: react_tucita_frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile.dev
      ports:
        - "5173:5173"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      environment:
        - CHOKIDAR_USEPOLLING=true

volumes:
  mysql_data:
    