# Generated by Django 4.2.5 on 2025-07-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tucita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='motivo_consulta',
            field=models.CharField(choices=[('Caries', 'Caries'), ('Consulta general', 'Consulta general'), ('Limpieza dental', 'Limpieza dental'), ('Endodoncia', 'Endodoncia'), ('Extracción dental', 'Extracción dental'), ('Atención de urgencia', 'Atención de urgencia'), ('Blanqueamiento dental', 'Blanqueamiento dental'), ('Ortodoncia', 'Ortodoncia'), ('Prótesis dental', 'Prótesis dental'), ('Consulta por dolor', 'Consulta por dolor'), ('Control de tratamiento', 'Control de tratamiento'), ('Consulta pediátrica', 'Consulta pediátrica'), ('Consulta estética', 'Consulta estética')], default='Consulta', max_length=50),
            preserve_default=False,
        ),
    ]
