# Generated by Django 4.2.5 on 2025-05-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_tucita', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='archivo_adjunto',
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='archivos_diagnosticos/')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='api_tucita.diagnostico')),
            ],
        ),
    ]
