# Generated by Django 4.2.5 on 2025-07-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tucita', '0003_paciente_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='Profesional',
            field=models.CharField(blank=True, default='Profesional de salud', max_length=50, null=True),
        ),
    ]
