# Generated by Django 4.2.5 on 2025-05-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_tucita', '0003_remove_diagnostico_archivo_adjunto_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='api_tucita.paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='api_tucita.profesional'),
        ),
    ]
