# Generated by Django 4.2.5 on 2025-07-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tucita', '0005_profesional_edad_profesional_ganancias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
